language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7

        - os: linux
          sudo: required
          python: 3.5

install:
    - sudo apt-get install -y python-lxml
    - pip install pep8 pytest-cov lxml
    - pip install -e .

script:
    - find . -name \*.py -exec pep8 --ignore=E501 {} \;
    - py.test ./tests/ -v --cov=Evtx
